# Setup
name:         JimQing's Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en/cn"
email:        jimqing@yeah.net

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown

# See change before re-build
